# Site settings
baseurl = "http://example.org" #without ending slash
languageCode = "en-us"
title = "Kate Zasada"
theme = "hugo-identity-theme"
themesDir = "themes"

# Disable unnecessary kinds
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]

# Enter your tracking code to enable Google Analytics
#googleAnalytics = "UA-22948479-1"

[params]
  
  # Images settings
  # Icons, backgrounds and avatars folders are placed in theme's static/images folder.
  # You may place your images in corresponding folders and then set only filenames below to
  # change page's appearance
  
  # Site icons
  favicon_ico = "favicon.ico"
  favicon_ico_sizes = "16x16 32x32"
  appleicon = "apple.png"

  # Additional options to supplement icons served
  #favicon_png = "favicon.png"
  #favicon_png_sizes = "96x96"
  #favicon_svg = "favicon.svg"

  # Link custom assets relative to /static
  #custom_js  = [""]
  #custom_css = ["background.css", "icons.css"]

  # Customization switches
  # Overwrite FontAwesome: see icons.css
  #custom_icons = true
  # Overwrite background: see background.css
  #custom_background = true

  # Personal data
  [params.personal]
    # If name is not set, author is used
    name = "Kate Zasada"
    # Avatars can be written to images/avatars/
    avatar = "kate.jpg"
    position = "Product Manager"
    livesIn = "New York"
    scope = [
        "Senior Product Manager at [BuzzFeed](https://www.buzzfeed.com?ref=kate)",
        "Instructor at [General Assembly](https://www.ga.co)",
        "Alumni of [Esty](https://www.Etsy.com), [Shapeways](https://www.shapeways.com), [Paribus](https://www.paribus.co), [PowerMyLearning](https://www.powermylearning.com), [Northeastern University](https://www.neu.edu)"
      ]
    biography = """Kate Zasada is a user-focused product manager in NYC. She loves working on consumer products and bridging the gap between technologists and their markets. Feel free to reach out about working together or to share your favorite adorable puppy pictures at kate@kzasada.com."""


    #[[params.contact.fields.hidden]]
    # Special values for name such as "page" and "site" will be autofilled
    #  name = "page"

  # Social settings
  # You may change these with your social links or add others

  [[params.social]]
    title = "Twitter"
    icon = "fa-twitter"
    link = "https://www.twitter.com/kzasada"

  [[params.social]]
    title = "Instagram"
    icon = "fa-instagram"
    link = "https://www.instagram.com/kzasada"
    
  [[params.social]]
    title = "Github"
    icon = "fa-github"
    link = "https://www.github.com/kzasada"

  # Footer settings
  [params.footer]
    # If copyright is not set, author is used
    copyright = "Kzasada Inc"

  # Page license
  [params.license]
    link = "https://creativecommons.org/licenses/by-sa/4.0/legalcode"
    name = "CC-BY-SA-4.0"

  # Credits
  [[params.credits]]
    # Title is used as URL text
    title = "HTML5UP"
    # Text will be used to explain the credit
    text = "Design by"
    link = "https://html5up.net"

  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="
